import 'package:uuid/uuid.dart';
import '../models/enums.dart';
import '../models/goal.dart';
import '../models/sub_task.dart';
import 'focus_list_service.dart';
import 'goal_repository.dart';

class GoalService {
  final GoalRepository _repository;
  final FocusListService _focus;
  final _uuid = const Uuid();

  GoalService(this._repository, this._focus);

  // --- Goal operations ---

  void addGoal(Goal goal) => _repository.save(goal);

  void removeGoal(String goalId) {
    _focus.dropGoal(goalId);
    _repository.delete(goalId);
  }

  void archiveGoal(String goalId) {
    final goal = _repository.findById(goalId);
    if (goal == null) return;
    goal.status = GoalStatus.archived;
    _focus.dropGoal(goalId);
    _repository.save(goal);
  }

  void restoreGoal(String goalId) {
    final goal = _repository.findById(goalId);
    if (goal == null) return;
    final allDone = goal.subtasks.isNotEmpty &&
        goal.subtasks.every((t) => t.state == SubTaskState.completed);
    goal.status = allDone ? GoalStatus.completed : GoalStatus.active;
    _repository.save(goal);
  }

  // Transitions an inbox (planning) goal to active. Triggered by the
  // "Queue Goal" button on the planning screen. If every subtask happens
  // to already be marked complete, the goal lands on completed instead.
  void queueGoal(String goalId) {
    final goal = _repository.findById(goalId);
    if (goal == null) return;
    if (goal.status != GoalStatus.inbox) return;
    final allDone = goal.subtasks.isNotEmpty &&
        goal.subtasks.every((t) => t.state == SubTaskState.completed);
    goal.status = allDone ? GoalStatus.completed : GoalStatus.active;
    _repository.save(goal);
  }

  // Returns a completed goal to the planning (inbox) stage so it can be
  // re-planned and re-queued. Resets all subtask states to pending so the
  // goal can be executed again from scratch.
  void sendToPlanning(String goalId) {
    final goal = _repository.findById(goalId);
    if (goal == null) return;
    goal.status = GoalStatus.inbox;
    for (final subtask in goal.subtasks) {
      subtask.state = SubTaskState.pending;
    }
    _focus.dropGoal(goalId);
    _repository.save(goal);
  }

  void clearArchive() {
    for (final goal in _repository.all
        .where((g) => g.status == GoalStatus.archived)
        .toList()) {
      _repository.delete(goal.goalId);
    }
  }

  void updateGoal(
    String goalId, {
    String? title,
    String? notes,
    GoalDifficulty? difficulty,
  }) {
    final goal = _repository.findById(goalId);
    if (goal == null) return;

    if (title != null) goal.title = title;
    if (notes != null) goal.notes = notes;
    if (difficulty != null) goal.difficulty = difficulty;
    _repository.save(goal);
  }

  /// Sets the emoji for a goal (generated by the LLM or set manually).
  void setEmoji(String goalId, String emoji) {
    final goal = _repository.findById(goalId);
    if (goal == null) return;
    goal.emoji = emoji;
    _repository.save(goal);
  }

  /// Clears the emoji for a goal.
  void clearEmoji(String goalId) {
    final goal = _repository.findById(goalId);
    if (goal == null) return;
    goal.emoji = null;
    _repository.save(goal);
  }

  /// Bulk-sets emojis for multiple goals in one batch.
  /// Efficient for post-enable generation across all existing goals.
  void bulkSetEmojis(Map<String, String> goalIdToEmoji) {
    for (final entry in goalIdToEmoji.entries) {
      final goal = _repository.findById(entry.key);
      if (goal == null) continue;
      goal.emoji = entry.value;
      _repository.save(goal);
    }
  }

  /// Sets or clears the due date. Pass null to remove it.
  void setDueDate(String goalId, DateTime? dueDate) {
    final goal = _repository.findById(goalId);
    if (goal == null) return;
    goal.dueDate = dueDate;
    _repository.save(goal);
  }

  // --- SubTask operations ---
  //
  // The `_reconcileFocus*` helpers keep [FocusListService] in step with the
  // canonical goal state. We diff old vs new subtask IDs after each mutation
  // and let the focus service add/remove entries as needed — that way no
  // call site has to know about focus internals, and the auto-include
  // behavior for fully-focused goals is enforced in one place.

  void addSubTask(String goalId, String description) {
    final goal = _repository.findById(goalId);
    if (goal == null) return;

    final newSubtask =
        SubTask(subtaskId: _uuid.v4(), description: description);
    goal.addSubTask(newSubtask);
    _repository.save(goal);
    _focus.onSubtasksAddedToGoal(goalId, [newSubtask.subtaskId]);
  }

  // Appends multiple new subtasks to the end of the pending list.
  // Used by the AI "add steps" flow when the user asks for specific additions
  // rather than a full re-decomposition.
  void appendSubTasks(String goalId, List<String> descriptions) {
    if (descriptions.isEmpty) return;
    final goal = _repository.findById(goalId);
    if (goal == null) return;
    final newSubtasks = descriptions
        .map((d) => SubTask(subtaskId: _uuid.v4(), description: d))
        .toList();
    for (final st in newSubtasks) {
      goal.addSubTask(st);
    }
    _repository.save(goal);
    _focus.onSubtasksAddedToGoal(
        goalId, newSubtasks.map((s) => s.subtaskId).toList());
  }

  // Replaces all subtasks on a goal with a fresh set of descriptions.
  // Used by the re-decompose flow to swap in AI-generated steps.
  void replaceAllSubTasks(String goalId, List<String> descriptions) {
    if (descriptions.isEmpty) return;
    final goal = _repository.findById(goalId);
    if (goal == null) return;
    goal.replaceAllSubTasks(
      descriptions
          .map((d) => SubTask(subtaskId: _uuid.v4(), description: d))
          .toList(),
    );
    _repository.save(goal);
    _focus.reconcileAfterBulkMutation(goal);
  }

  // Replaces only the pending subtasks, preserving any already-completed steps.
  // Used by the re-decompose flow when the user opts to keep completed steps.
  void replacePendingSubTasks(String goalId, List<String> descriptions) {
    if (descriptions.isEmpty) return;
    final goal = _repository.findById(goalId);
    if (goal == null) return;
    goal.replacePendingSubTasks(
      descriptions
          .map((d) => SubTask(subtaskId: _uuid.v4(), description: d))
          .toList(),
    );
    _repository.save(goal);
    _focus.reconcileAfterBulkMutation(goal);
  }

  // Replaces a single subtask with one or more smaller steps. Used both by
  // the manual split flow (user types replacements) and the LLM-driven
  // breakdown flow (provider returns 1–3 replacement descriptions).
  void splitSubTask(
    String goalId,
    String subtaskId,
    List<String> descriptions,
  ) {
    if (descriptions.isEmpty) return;
    final goal = _repository.findById(goalId);
    if (goal == null) return;
    final newSubtasks = descriptions
        .map((d) => SubTask(subtaskId: _uuid.v4(), description: d))
        .toList();
    final wasFocused = _focus.isInFocus(goalId, subtaskId);
    final goalFull = _focus.isGoalFullyFocused(goalId);
    goal.replaceSubTask(subtaskId, newSubtasks);
    _repository.save(goal);

    if (wasFocused || goalFull) {
      _focus.replaceEntry(
        goalId,
        subtaskId,
        newSubtasks.map((s) => s.subtaskId).toList(),
      );
    } else {
      _focus.removeDanglingEntry(goalId, subtaskId);
    }
  }

  void deleteSubTask(String goalId, String subtaskId) {
    final goal = _repository.findById(goalId);
    if (goal == null) return;

    goal.removeSubTask(subtaskId);
    _repository.save(goal);
    _focus.removeDanglingEntry(goalId, subtaskId);
  }

  void updateSubTaskDescription(
    String goalId,
    String subtaskId,
    String newDescription,
  ) {
    final goal = _repository.findById(goalId);
    if (goal == null) return;
    final subtask = goal.subtasks.firstWhere((t) => t.subtaskId == subtaskId);
    subtask.updateDescription(newDescription);
    _repository.save(goal);
  }

  void reorderSubTask(String goalId, int oldIndex, int newIndex) {
    final goal = _repository.findById(goalId);
    if (goal == null) return;
    goal.reorderSubTask(oldIndex, newIndex);
    _repository.save(goal);
  }

  void completeCurrentSubTask(String goalId) {
    final goal = _repository.findById(goalId);
    if (goal == null) return;
    goal.completeCurrentSubTask();
    _repository.save(goal);
  }

  /// Completes a specific subtask by id. Differs from
  /// [completeCurrentSubTask] in that the target need not be the goal's
  /// current step — the Focus screen lets the user knock off any focused
  /// subtask, even one that's mid-sequence within its parent goal.
  void completeSubTask(String goalId, String subtaskId) {
    final goal = _repository.findById(goalId);
    if (goal == null) return;
    final subtask = goal.subtasks
        .where((t) => t.subtaskId == subtaskId)
        .firstOrNull;
    if (subtask == null || subtask.state == SubTaskState.completed) return;
    subtask.markComplete();
    // Recalculate goal status by going through the same path as the
    // model's _recalculateStatus (called from completeCurrentSubTask).
    final allDone =
        goal.subtasks.every((t) => t.state == SubTaskState.completed);
    if (allDone &&
        goal.status != GoalStatus.archived &&
        goal.status != GoalStatus.inbox) {
      goal.status = GoalStatus.completed;
    }
    _repository.save(goal);
  }

  void uncompleteSubTask(String goalId, String subtaskId) {
    final goal = _repository.findById(goalId);
    if (goal == null) return;
    goal.uncompleteSubTask(subtaskId);
    _repository.save(goal);
  }

}
