import 'package:flutter/material.dart';

/// A single entry in the icon catalog.
class IconEntry {
  final String name;   // stored in Goal.emoji
  final String label;  // shown in picker / used for search
  final IconData icon;

  const IconEntry(this.name, this.label, this.icon);
}

/// A named category grouping icon entries for display in the picker.
class IconCategory {
  final String title;
  final List<IconEntry> entries;

  const IconCategory(this.title, this.entries);
}

/// The full curated catalog, grouped by category.
///
/// To add a new icon: pick any IconData constant, give it a short label,
/// choose a unique [name] key (stored in Goal.emoji), and drop it into the
/// appropriate category. Names must be unique across all categories.
const List<IconCategory> iconCatalog = [
  IconCategory('Work & Career', [
    IconEntry('work', 'Work', Icons.work_outline),
    IconEntry('business', 'Business', Icons.business_center_outlined),
    IconEntry('task', 'Task', Icons.assignment_outlined),
    IconEntry('goal_flag', 'Goal', Icons.flag_outlined),
    IconEntry('growth', 'Growth', Icons.trending_up),
    IconEntry('analytics', 'Analytics', Icons.bar_chart),
    IconEntry('schedule', 'Schedule', Icons.schedule_outlined),
    IconEntry('event', 'Event', Icons.event_outlined),
    IconEntry('deal', 'Deal', Icons.handshake_outlined),
    IconEntry('launch', 'Launch', Icons.rocket_launch_outlined),
    IconEntry('trophy', 'Trophy', Icons.emoji_events_outlined),
    IconEntry('meeting', 'Meeting', Icons.people_outlined),
    IconEntry('presentation', 'Present', Icons.present_to_all_outlined),
    IconEntry('checklist', 'Checklist', Icons.checklist_outlined),
    IconEntry('manage', 'Manage', Icons.manage_accounts_outlined),
    IconEntry('insights', 'Insights', Icons.insights_outlined),
    IconEntry('leaderboard', 'Leaderboard', Icons.leaderboard_outlined),
    IconEntry('campaign', 'Campaign', Icons.campaign_outlined),
    IconEntry('supervisor', 'Lead', Icons.supervisor_account_outlined),
    IconEntry('pending', 'Pending', Icons.pending_actions_outlined),
    IconEntry('verified', 'Verified', Icons.verified_outlined),
    IconEntry('sell', 'Sales', Icons.sell_outlined),
    IconEntry('receipt', 'Receipt', Icons.receipt_long_outlined),
    IconEntry('ads_click', 'Marketing', Icons.ads_click_outlined),
    IconEntry('price_check', 'Pricing', Icons.price_check_outlined),
    IconEntry('new_release', 'Release', Icons.new_releases_outlined),
    IconEntry('inventory', 'Inventory', Icons.inventory_2_outlined),
    IconEntry('hub', 'Hub', Icons.hub_outlined),
    IconEntry('badge', 'Badge', Icons.badge_outlined),
    IconEntry('cases', 'Cases', Icons.cases_outlined),
    IconEntry('engineering', 'Engineering', Icons.engineering_outlined),
    IconEntry('architecture', 'Architect', Icons.architecture),
    IconEntry('construction', 'Build', Icons.construction),
    IconEntry('local_shipping', 'Shipping', Icons.local_shipping_outlined),
    IconEntry('print', 'Print', Icons.print_outlined),
    IconEntry('gavel', 'Legal', Icons.gavel),
    IconEntry('account_tree', 'Org Chart', Icons.account_tree_outlined),
    IconEntry('qr_code', 'QR Code', Icons.qr_code_outlined),
    IconEntry('document_scanner', 'Scanner', Icons.document_scanner_outlined),
    IconEntry('policy', 'Policy', Icons.policy_outlined),
    IconEntry('rule', 'Rules', Icons.rule_outlined),
    IconEntry('workspaces', 'Workspace', Icons.workspaces_outlined),
    IconEntry('troubleshoot', 'Troubleshoot', Icons.troubleshoot_outlined),
    IconEntry('speed', 'KPIs', Icons.speed_outlined),
    IconEntry('precision_mfg', 'Manufacturing', Icons.precision_manufacturing_outlined),
    IconEntry('factory', 'Factory', Icons.factory_outlined),
    IconEntry('conveyor', 'Warehouse', Icons.warehouse_outlined),
    IconEntry('contract', 'Contract', Icons.description_outlined),
    IconEntry('diversity_work', 'Diversity', Icons.diversity_3),
  ]),
  IconCategory('Health & Fitness', [
    IconEntry('gym', 'Gym', Icons.fitness_center_outlined),
    IconEntry('meditation', 'Meditate', Icons.self_improvement_outlined),
    IconEntry('running', 'Running', Icons.directions_run_outlined),
    IconEntry('cycling', 'Cycling', Icons.directions_bike_outlined),
    IconEntry('swimming', 'Swimming', Icons.pool_outlined),
    IconEntry('tennis', 'Tennis', Icons.sports_tennis_outlined),
    IconEntry('basketball', 'Basketball', Icons.sports_basketball_outlined),
    IconEntry('soccer', 'Soccer', Icons.sports_soccer_outlined),
    IconEntry('gymnastics', 'Gymnastics', Icons.sports_gymnastics),
    IconEntry('hiking', 'Hiking', Icons.hiking_outlined),
    IconEntry('martial_arts', 'Martial Arts', Icons.sports_martial_arts),
    IconEntry('skiing', 'Skiing', Icons.downhill_skiing_outlined),
    IconEntry('spa', 'Spa', Icons.spa_outlined),
    IconEntry('heartbeat', 'Heart', Icons.favorite_border),
    IconEntry('sleep', 'Sleep', Icons.bedtime_outlined),
    IconEntry('nordic_walk', 'Nordic Walk', Icons.nordic_walking_outlined),
    IconEntry('roller_skate', 'Roller Skate', Icons.roller_skating_outlined),
    IconEntry('ice_skate', 'Ice Skate', Icons.ice_skating_outlined),
    IconEntry('skateboard', 'Skateboard', Icons.skateboarding_outlined),
    IconEntry('surfing', 'Surfing', Icons.surfing_outlined),
    IconEntry('kitesurfing', 'Kite Surf', Icons.kitesurfing_outlined),
    IconEntry('scuba', 'Scuba Dive', Icons.scuba_diving_outlined),
    IconEntry('snowshoe', 'Snowshoe', Icons.snowshoeing_outlined),
    IconEntry('rowing', 'Rowing', Icons.rowing_outlined),
    IconEntry('sledding', 'Sledding', Icons.sledding_outlined),
    IconEntry('mood', 'Mood', Icons.mood_outlined),
    IconEntry('whatshot', 'Streak', Icons.whatshot_outlined),
    IconEntry('medical', 'Medical', Icons.medical_services_outlined),
    IconEntry('vaccine', 'Health', Icons.health_and_safety_outlined),
    IconEntry('monitor_heart', 'Vitals', Icons.monitor_heart_outlined),
    IconEntry('volleyball', 'Volleyball', Icons.sports_volleyball_outlined),
    IconEntry('baseball', 'Baseball', Icons.sports_baseball_outlined),
    IconEntry('football', 'Football', Icons.sports_football_outlined),
    IconEntry('cricket', 'Cricket', Icons.sports_cricket_outlined),
    IconEntry('golf', 'Golf', Icons.sports_golf_outlined),
    IconEntry('hockey', 'Hockey', Icons.sports_hockey),
    IconEntry('kabaddi', 'Kabaddi', Icons.sports_kabaddi),
    IconEntry('handball', 'Handball', Icons.sports_handball),
    IconEntry('rugby', 'Rugby', Icons.sports_rugby),
    IconEntry('esports', 'Esports', Icons.sports_esports_outlined),
    IconEntry('hospital', 'Hospital', Icons.local_hospital_outlined),
    IconEntry('medication', 'Medication', Icons.medication_outlined),
    IconEntry('pharmacy', 'Pharmacy', Icons.local_pharmacy_outlined),
    IconEntry('bloodtype', 'Blood Type', Icons.bloodtype_outlined),
    IconEntry('vaccines', 'Vaccines', Icons.vaccines_outlined),
    IconEntry('accessible', 'Accessible', Icons.accessible_outlined),
    IconEntry('stroller', 'Stroller', Icons.stroller_outlined),
    IconEntry('baby', 'Baby', Icons.child_care_outlined),
    IconEntry('scale', 'Weight', Icons.scale_outlined),
    IconEntry('nutrition', 'Nutrition', Icons.set_meal_outlined),
  ]),
  IconCategory('Learning & Mind', [
    IconEntry('school', 'School', Icons.school_outlined),
    IconEntry('book', 'Book', Icons.book_outlined),
    IconEntry('reading', 'Reading', Icons.auto_stories_outlined),
    IconEntry('mind', 'Mind', Icons.psychology_outlined),
    IconEntry('idea', 'Idea', Icons.lightbulb_outline),
    IconEntry('writing', 'Writing', Icons.edit_outlined),
    IconEntry('science', 'Science', Icons.science_outlined),
    IconEntry('research', 'Research', Icons.biotech_outlined),
    IconEntry('language', 'Language', Icons.language_outlined),
    IconEntry('history', 'History', Icons.history_edu_outlined),
    IconEntry('therapy', 'Therapy', Icons.psychology_alt_outlined),
    IconEntry('quiz', 'Quiz', Icons.quiz_outlined),
    IconEntry('calculate', 'Math', Icons.calculate_outlined),
    IconEntry('translate', 'Translate', Icons.translate_outlined),
    IconEntry('certificate', 'Certificate', Icons.workspace_premium_outlined),
    IconEntry('article', 'Article', Icons.article_outlined),
    IconEntry('newspaper', 'News', Icons.newspaper_outlined),
    IconEntry('edit_note', 'Notes', Icons.edit_note_outlined),
    IconEntry('bookmark', 'Bookmark', Icons.bookmark_border_outlined),
    IconEntry('import_contacts', 'Contacts', Icons.import_contacts_outlined),
    IconEntry('forum', 'Forum', Icons.forum_outlined),
    IconEntry('menu_book', 'Textbook', Icons.menu_book_outlined),
    IconEntry('school_alt', 'Teach', Icons.cast_for_education_outlined),
    IconEntry('library', 'Library', Icons.local_library_outlined),
    IconEntry('format_paint', 'Highlight', Icons.format_paint_outlined),
    IconEntry('grade', 'Grade', Icons.grade_outlined),
    IconEntry('stars', 'Stars', Icons.stars_outlined),
    IconEntry('feed', 'Feed', Icons.feed_outlined),
    IconEntry('pending_study', 'Plan', Icons.pending_actions_outlined),
    IconEntry('create', 'Create', Icons.create_outlined),
    IconEntry('microscope', 'Microscope', Icons.biotech_outlined),
    IconEntry('schema', 'Schema', Icons.schema_outlined),
    IconEntry('data_usage', 'Data', Icons.data_usage_outlined),
    IconEntry('functions', 'Functions', Icons.functions_outlined),
    IconEntry('class_room', 'Classroom', Icons.class_outlined),
    IconEntry('assignment_turned', 'Done', Icons.assignment_turned_in_outlined),
    IconEntry('rocket_learn', 'Space', Icons.rocket_outlined),
    IconEntry('explore_learn', 'Explore', Icons.explore_outlined),
    IconEntry('collections', 'Collection', Icons.collections_outlined),
    IconEntry('draw_learn', 'Draw', Icons.draw_outlined),
    IconEntry('format_quote', 'Quote', Icons.format_quote_outlined),
    IconEntry('map_learn', 'Map', Icons.map_outlined),
    IconEntry('emoji_objects', 'Objects', Icons.emoji_objects_outlined),
    IconEntry('memory_learn', 'Memory', Icons.memory_outlined),
    IconEntry('abc', 'Alphabet', Icons.abc_outlined),
    IconEntry('number_9', 'Numbers', Icons.looks_one_outlined),
    IconEntry('architecture_learn', 'Design', Icons.architecture),
    IconEntry('terminal_learn', 'Code', Icons.terminal_outlined),
    IconEntry('developer_learn', 'Developer', Icons.developer_mode_outlined),
    IconEntry('hub_learn', 'Network', Icons.hub_outlined),
  ]),
  IconCategory('Food & Drink', [
    IconEntry('coffee', 'Coffee', Icons.coffee_outlined),
    IconEntry('cafe', 'Café', Icons.local_cafe_outlined),
    IconEntry('restaurant', 'Restaurant', Icons.restaurant_outlined),
    IconEntry('pizza', 'Pizza', Icons.local_pizza_outlined),
    IconEntry('fastfood', 'Fast Food', Icons.fastfood_outlined),
    IconEntry('grilling', 'Grilling', Icons.outdoor_grill_outlined),
    IconEntry('baking', 'Baking', Icons.bakery_dining_outlined),
    IconEntry('ramen', 'Noodles', Icons.ramen_dining_outlined),
    IconEntry('meal_prep', 'Meal Prep', Icons.set_meal_outlined),
    IconEntry('wine', 'Wine', Icons.wine_bar_outlined),
    IconEntry('bar', 'Bar', Icons.local_bar_outlined),
    IconEntry('kitchen', 'Kitchen', Icons.kitchen_outlined),
    IconEntry('dinner', 'Dinner', Icons.dinner_dining_outlined),
    IconEntry('lunch', 'Lunch', Icons.lunch_dining_outlined),
    IconEntry('brunch', 'Brunch', Icons.brunch_dining_outlined),
    IconEntry('tapas', 'Tapas', Icons.tapas_outlined),
    IconEntry('kebab', 'Kebab', Icons.kebab_dining_outlined),
    IconEntry('rice', 'Rice', Icons.rice_bowl_outlined),
    IconEntry('icecream', 'Ice Cream', Icons.icecream_outlined),
    IconEntry('cake', 'Cake', Icons.cake_outlined),
    IconEntry('cookie', 'Cookie', Icons.cookie_outlined),
    IconEntry('egg', 'Egg', Icons.egg_outlined),
    IconEntry('flatware', 'Cutlery', Icons.flatware_outlined),
    IconEntry('blender', 'Smoothie', Icons.blender_outlined),
    IconEntry('liquor', 'Spirits', Icons.liquor_outlined),
    IconEntry('water_glass', 'Water', Icons.local_drink_outlined),
    IconEntry('emoji_food', 'Food', Icons.emoji_food_beverage_outlined),
    IconEntry('food_bank', 'Food Bank', Icons.food_bank_outlined),
    IconEntry('soup', 'Soup', Icons.soup_kitchen_outlined),
    IconEntry('local_dining', 'Dining', Icons.local_dining_outlined),
    IconEntry('grocery', 'Grocery', Icons.local_grocery_store_outlined),
    IconEntry('produce', 'Produce', Icons.energy_savings_leaf_outlined),
    IconEntry('microwave', 'Microwave', Icons.microwave_outlined),
    IconEntry('countertops', 'Counter', Icons.countertops_outlined),
    IconEntry('breakfast', 'Breakfast', Icons.free_breakfast_outlined),
    IconEntry('no_drinks', 'No Alcohol', Icons.no_drinks_outlined),
    IconEntry('no_food', 'Diet', Icons.no_food_outlined),
    IconEntry('hot_drink', 'Hot Drink', Icons.coffee_maker_outlined),
    IconEntry('sports_bar', 'Sports Bar', Icons.sports_bar_outlined),
    IconEntry('takeout', 'Takeout', Icons.takeout_dining_outlined),
  ]),
  IconCategory('Home & Garden', [
    IconEntry('home', 'Home', Icons.home_outlined),
    IconEntry('house', 'House', Icons.house_outlined),
    IconEntry('cabin', 'Cabin', Icons.cabin_outlined),
    IconEntry('garden', 'Garden', Icons.yard_outlined),
    IconEntry('park', 'Park', Icons.park_outlined),
    IconEntry('flowers', 'Flowers', Icons.local_florist_outlined),
    IconEntry('eco', 'Eco', Icons.eco_outlined),
    IconEntry('grass', 'Lawn', Icons.grass_outlined),
    IconEntry('diy', 'DIY', Icons.handyman_outlined),
    IconEntry('cleaning', 'Clean', Icons.cleaning_services_outlined),
    IconEntry('nature_leaf', 'Nature', Icons.nature_outlined),
    IconEntry('water_drop', 'Watering', Icons.water_drop_outlined),
    IconEntry('fireplace', 'Fireplace', Icons.fireplace_outlined),
    IconEntry('hot_tub', 'Hot Tub', Icons.hot_tub_outlined),
    IconEntry('deck', 'Deck', Icons.deck_outlined),
    IconEntry('fence', 'Fence', Icons.fence_outlined),
    IconEntry('balcony', 'Balcony', Icons.balcony_outlined),
    IconEntry('plumbing', 'Plumbing', Icons.plumbing_outlined),
    IconEntry('roofing', 'Roofing', Icons.roofing_outlined),
    IconEntry('foundation', 'Build', Icons.foundation_outlined),
    IconEntry('garage', 'Garage', Icons.garage_outlined),
    IconEntry('cottage', 'Cottage', Icons.cottage_outlined),
    IconEntry('villa', 'Villa', Icons.villa_outlined),
    IconEntry('bungalow', 'Bungalow', Icons.bungalow_outlined),
    IconEntry('chalet', 'Chalet', Icons.chalet_outlined),
    IconEntry('apartment', 'Apartment', Icons.apartment_outlined),
    IconEntry('chair', 'Furniture', Icons.chair_outlined),
    IconEntry('bed', 'Bedroom', Icons.bed_outlined),
    IconEntry('bathtub', 'Bathtub', Icons.bathtub_outlined),
    IconEntry('shower', 'Shower', Icons.shower_outlined),
    IconEntry('lightbulb_home', 'Lighting', Icons.lightbulb_outline),
    IconEntry('electrical', 'Electrical', Icons.electrical_services_outlined),
    IconEntry('outlet', 'Outlet', Icons.outlet_outlined),
    IconEntry('thermostat', 'Thermostat', Icons.thermostat_outlined),
    IconEntry('ac_home', 'AC', Icons.ac_unit_outlined),
    IconEntry('sensor_door', 'Door', Icons.sensor_door_outlined),
    IconEntry('window', 'Window', Icons.window_outlined),
    IconEntry('stairs', 'Stairs', Icons.stairs_outlined),
    IconEntry('elevator', 'Elevator', Icons.elevator_outlined),
    IconEntry('laundry', 'Laundry', Icons.local_laundry_service_outlined),
    IconEntry('iron', 'Ironing', Icons.iron_outlined),
    IconEntry('smoke_det', 'Safety', Icons.warning_amber_outlined),
    IconEntry('solar_home', 'Solar', Icons.solar_power_outlined),
    IconEntry('heat_pump', 'Heat Pump', Icons.heat_pump_outlined),
    IconEntry('pool_home', 'Pool', Icons.pool_outlined),
    IconEntry('table_bar', 'Table', Icons.table_bar_outlined),
    IconEntry('desk', 'Desk', Icons.desk_outlined),
    IconEntry('door_front', 'Door', Icons.meeting_room_outlined),
    IconEntry('storage_home', 'Storage', Icons.storage_outlined),
    IconEntry('move', 'Moving', Icons.open_with_outlined),
  ]),
  IconCategory('Travel & Nature', [
    IconEntry('explore', 'Explore', Icons.travel_explore_outlined),
    IconEntry('landscape', 'Landscape', Icons.landscape_outlined),
    IconEntry('beach', 'Beach', Icons.beach_access_outlined),
    IconEntry('world', 'World', Icons.public_outlined),
    IconEntry('flight', 'Travel', Icons.flight_outlined),
    IconEntry('road_trip', 'Road Trip', Icons.directions_car_outlined),
    IconEntry('sailing', 'Sailing', Icons.sailing_outlined),
    IconEntry('kayaking', 'Kayaking', Icons.kayaking_outlined),
    IconEntry('snowboarding', 'Snowboard', Icons.snowboarding_outlined),
    IconEntry('paragliding', 'Paraglide', Icons.paragliding_outlined),
    IconEntry('sunny', 'Sunshine', Icons.wb_sunny_outlined),
    IconEntry('forest', 'Forest', Icons.forest_outlined),
    IconEntry('terrain', 'Terrain', Icons.terrain_outlined),
    IconEntry('nature_people', 'Nature', Icons.nature_people_outlined),
    IconEntry('agriculture', 'Farm', Icons.agriculture_outlined),
    IconEntry('water_wave', 'Water', Icons.water_outlined),
    IconEntry('storm', 'Storm', Icons.storm_outlined),
    IconEntry('thunderstorm', 'Thunder', Icons.thunderstorm_outlined),
    IconEntry('tornado', 'Tornado', Icons.tornado_outlined),
    IconEntry('volcano', 'Volcano', Icons.volcano_outlined),
    IconEntry('ac_unit', 'Winter', Icons.ac_unit_outlined),
    IconEntry('ferry', 'Ferry', Icons.directions_ferry_outlined),
    IconEntry('electric_car', 'EV', Icons.electric_car_outlined),
    IconEntry('moped', 'Moped', Icons.moped_outlined),
    IconEntry('pedal_bike', 'Bike', Icons.pedal_bike_outlined),
    IconEntry('airport', 'Airport', Icons.local_airport_outlined),
    IconEntry('luggage', 'Luggage', Icons.luggage_outlined),
    IconEntry('hotel', 'Hotel', Icons.hotel_outlined),
    IconEntry('map', 'Map', Icons.map_outlined),
    IconEntry('compass', 'Compass', Icons.explore_outlined),
    IconEntry('tsunami', 'Wave', Icons.tsunami_outlined),
    IconEntry('nights_stay', 'Night', Icons.nights_stay_outlined),
    IconEntry('wb_cloudy', 'Cloudy', Icons.wb_cloudy_outlined),
    IconEntry('rainbow', 'Rainbow', Icons.filter_drama_outlined),
    IconEntry('camping', 'Camping', Icons.outdoor_grill_outlined),
    IconEntry('attractions', 'Attraction', Icons.attractions_outlined),
    IconEntry('museum_t', 'Museum', Icons.museum_outlined),
    IconEntry('monument', 'Monument', Icons.account_balance_outlined),
    IconEntry('national_park', 'National Park', Icons.park_outlined),
    IconEntry('cabin_t', 'Cabin', Icons.cabin_outlined),
    IconEntry('temple_b', 'Temple', Icons.temple_buddhist_outlined),
    IconEntry('church_t', 'Church', Icons.church_outlined),
    IconEntry('mosque_t', 'Mosque', Icons.mosque_outlined),
    IconEntry('hot_spring', 'Hot Spring', Icons.hot_tub_outlined),
    IconEntry('snorkeling', 'Snorkel', Icons.scuba_diving_outlined),
    IconEntry('local_see', 'Sightseeing', Icons.local_see_outlined),
    IconEntry('photo_spot', 'Photo Spot', Icons.photo_camera_outlined),
    IconEntry('navigation_t', 'Navigate', Icons.navigation_outlined),
    IconEntry('pin_drop', 'Pin Drop', Icons.pin_drop_outlined),
    IconEntry('route', 'Route', Icons.alt_route_outlined),
  ]),
  IconCategory('Creative & Arts', [
    IconEntry('art', 'Art', Icons.palette_outlined),
    IconEntry('music', 'Music', Icons.music_note_outlined),
    IconEntry('podcast', 'Podcast', Icons.podcasts_outlined),
    IconEntry('photography', 'Photo', Icons.photo_camera_outlined),
    IconEntry('film', 'Film', Icons.movie_outlined),
    IconEntry('painting', 'Painting', Icons.brush_outlined),
    IconEntry('gaming', 'Gaming', Icons.games_outlined),
    IconEntry('piano', 'Piano', Icons.piano_outlined),
    IconEntry('theater', 'Theater', Icons.theater_comedy_outlined),
    IconEntry('design', 'Design', Icons.draw_outlined),
    IconEntry('crafts', 'Crafts', Icons.content_cut_outlined),
    IconEntry('style', 'Style', Icons.style_outlined),
    IconEntry('album', 'Album', Icons.album_outlined),
    IconEntry('audiotrack', 'Track', Icons.audiotrack_outlined),
    IconEntry('playlist', 'Playlist', Icons.queue_music_outlined),
    IconEntry('library_music', 'Music Lib', Icons.library_music_outlined),
    IconEntry('headphones', 'Headphones', Icons.headphones_outlined),
    IconEntry('radio', 'Radio', Icons.radio_outlined),
    IconEntry('live_tv', 'Live', Icons.live_tv_outlined),
    IconEntry('video_cam', 'Video', Icons.videocam_outlined),
    IconEntry('photo_library', 'Photos', Icons.photo_library_outlined),
    IconEntry('color_lens', 'Colour', Icons.color_lens_outlined),
    IconEntry('filter_vintage', 'Vintage', Icons.filter_vintage_outlined),
    IconEntry('wallpaper', 'Wallpaper', Icons.wallpaper_outlined),
    IconEntry('auto_fix', 'Magic', Icons.auto_fix_high_outlined),
    IconEntry('animation', 'Animation', Icons.animation_outlined),
    IconEntry('mic_music', 'Mic', Icons.mic_outlined),
    IconEntry('speaker', 'Speaker', Icons.speaker_outlined),
    IconEntry('image_edit', 'Edit', Icons.image_outlined),
    IconEntry('extension_puzzle', 'Puzzle', Icons.extension_outlined),
    IconEntry('format_shapes', 'Shapes', Icons.format_shapes_outlined),
    IconEntry('gesture', 'Gesture', Icons.gesture_outlined),
    IconEntry('architecture_c', 'Blueprint', Icons.architecture),
    IconEntry('crop', 'Crop', Icons.crop_outlined),
    IconEntry('tune', 'Tune', Icons.tune_outlined),
    IconEntry('lens_blur', 'Bokeh', Icons.lens_blur_outlined),
    IconEntry('texture', 'Texture', Icons.texture_outlined),
    IconEntry('layers', 'Layers', Icons.layers_outlined),
    IconEntry('burst_mode', 'Burst', Icons.burst_mode_outlined),
    IconEntry('local_movies', 'Cinema', Icons.local_movies_outlined),
    IconEntry('theaters', 'Theaters', Icons.theaters_outlined),
    IconEntry('movie_filter', 'Film Fest', Icons.movie_filter_outlined),
    IconEntry('ondemand_video', 'Streaming', Icons.ondemand_video_outlined),
    IconEntry('subscriptions', 'Subscribe', Icons.subscriptions_outlined),
    IconEntry('collections_c', 'Gallery', Icons.collections_outlined),
    IconEntry('grid_view', 'Grid', Icons.grid_view_outlined),
    IconEntry('3d_rotation', '3D', Icons.rotate_90_degrees_ccw_outlined),
    IconEntry('emoji_symbols', 'Symbols', Icons.emoji_symbols_outlined),
    IconEntry('format_quote_c', 'Quote', Icons.format_quote_outlined),
    IconEntry('piano_key', 'Concert', Icons.piano_outlined),
  ]),
  IconCategory('Finance & Goals', [
    IconEntry('savings', 'Savings', Icons.savings_outlined),
    IconEntry('wallet', 'Wallet', Icons.account_balance_wallet_outlined),
    IconEntry('money', 'Money', Icons.monetization_on_outlined),
    IconEntry('bank', 'Bank', Icons.account_balance_outlined),
    IconEntry('diamond', 'Diamond', Icons.diamond_outlined),
    IconEntry('paid', 'Paid', Icons.paid_outlined),
    IconEntry('investment', 'Invest', Icons.price_change_outlined),
    IconEntry('shopping', 'Shopping', Icons.shopping_cart_outlined),
    IconEntry('store', 'Store', Icons.store_outlined),
    IconEntry('star_rating', 'Star', Icons.star_outline),
    IconEntry('award', 'Award', Icons.military_tech_outlined),
    IconEntry('target', 'Target', Icons.gps_fixed),
    IconEntry('loyalty', 'Loyalty', Icons.loyalty_outlined),
    IconEntry('redeem', 'Redeem', Icons.redeem_outlined),
    IconEntry('gift_card', 'Gift Card', Icons.card_giftcard_outlined),
    IconEntry('membership', 'Member', Icons.card_membership_outlined),
    IconEntry('bitcoin', 'Crypto', Icons.currency_bitcoin_outlined),
    IconEntry('exchange', 'Exchange', Icons.currency_exchange_outlined),
    IconEntry('percent', 'Percent', Icons.percent_outlined),
    IconEntry('attach_money', 'Cash', Icons.attach_money),
    IconEntry('shopping_bag', 'Bag', Icons.shopping_bag_outlined),
    IconEntry('storefront', 'Storefront', Icons.storefront_outlined),
    IconEntry('atm', 'ATM', Icons.local_atm_outlined),
    IconEntry('trending_f', 'Trending', Icons.trending_up),
    IconEntry('euro', 'Euro', Icons.euro_outlined),
    IconEntry('currency_pound', 'Pound', Icons.currency_pound_outlined),
    IconEntry('currency_yen', 'Yen', Icons.currency_yen_outlined),
    IconEntry('currency_franc', 'Franc', Icons.currency_franc_outlined),
    IconEntry('credit_card', 'Card', Icons.credit_card_outlined),
    IconEntry('contactless', 'Tap Pay', Icons.contactless_outlined),
    IconEntry('request_quote', 'Quote', Icons.request_quote_outlined),
    IconEntry('receipt_f', 'Receipt', Icons.receipt_outlined),
    IconEntry('point_of_sale', 'POS', Icons.point_of_sale_outlined),
    IconEntry('local_offer', 'Offer', Icons.local_offer_outlined),
    IconEntry('discount', 'Discount', Icons.discount_outlined),
    IconEntry('volunteer_f', 'Donate', Icons.volunteer_activism_outlined),
    IconEntry('donations', 'Charity', Icons.payments_outlined),
    IconEntry('real_estate', 'Property', Icons.real_estate_agent_outlined),
    IconEntry('home_loan', 'Mortgage', Icons.home_outlined),
    IconEntry('pie_chart', 'Portfolio', Icons.pie_chart_outline),
    IconEntry('show_chart', 'Chart', Icons.show_chart),
    IconEntry('candlestick', 'Trading', Icons.candlestick_chart_outlined),
    IconEntry('account_box', 'Account', Icons.account_box_outlined),
    IconEntry('premium', 'Premium', Icons.workspace_premium_outlined),
    IconEntry('military_tech', 'Achievement', Icons.military_tech_outlined),
    IconEntry('emoji_trophy', 'Trophy', Icons.emoji_events_outlined),
    IconEntry('flag_f', 'Milestone', Icons.outlined_flag),
    IconEntry('star_f', 'Favourite', Icons.star_border),
    IconEntry('rocket_f', 'Launch', Icons.rocket_launch_outlined),
    IconEntry('bolt_f', 'Energy', Icons.bolt_outlined),
  ]),
  IconCategory('People & Wellbeing', [
    IconEntry('people', 'People', Icons.people_outline),
    IconEntry('team', 'Team', Icons.groups_outlined),
    IconEntry('volunteer', 'Volunteer', Icons.volunteer_activism_outlined),
    IconEntry('family', 'Family', Icons.child_care_outlined),
    IconEntry('chat', 'Chat', Icons.chat_bubble_outline),
    IconEntry('community', 'Community', Icons.diversity_3),
    IconEntry('happy', 'Happy', Icons.sentiment_satisfied_outlined),
    IconEntry('social', 'Social', Icons.emoji_people_outlined),
    IconEntry('connect', 'Connect', Icons.connect_without_contact_outlined),
    IconEntry('accessibility', 'Wellbeing', Icons.accessibility_new_outlined),
    IconEntry('celebrate', 'Celebrate', Icons.celebration_outlined),
    IconEntry('emoji_emotion', 'Emotions', Icons.emoji_emotions_outlined),
    IconEntry('very_happy', 'Joy', Icons.sentiment_very_satisfied_outlined),
    IconEntry('face', 'Face', Icons.face_outlined),
    IconEntry('group_work', 'Group Work', Icons.group_work_outlined),
    IconEntry('announcement', 'Announce', Icons.announcement_outlined),
    IconEntry('feedback', 'Feedback', Icons.feedback_outlined),
    IconEntry('share', 'Share', Icons.share_outlined),
    IconEntry('record_voice', 'Voice', Icons.record_voice_over_outlined),
    IconEntry('interpreter', 'Interpret', Icons.interpreter_mode_outlined),
    IconEntry('elderly', 'Elder', Icons.elderly_outlined),
    IconEntry('person_pin', 'Person', Icons.person_pin_outlined),
    IconEntry('self_care', 'Self Care', Icons.spa_outlined),
    IconEntry('mood_p', 'Mood', Icons.mood_outlined),
    IconEntry('diversity2', 'Together', Icons.diversity_2_outlined),
    IconEntry('diversity1', 'Inclusion', Icons.diversity_1_outlined),
    IconEntry('waving_hand', 'Hello', Icons.waving_hand_outlined),
    IconEntry('handshake_p', 'Handshake', Icons.handshake_outlined),
    IconEntry('thumb_up', 'Like', Icons.thumb_up_alt_outlined),
    IconEntry('sentiment_neutral', 'Neutral', Icons.sentiment_neutral_outlined),
    IconEntry('sentiment_dissatisfied', 'Sad', Icons.sentiment_dissatisfied_outlined),
    IconEntry('night_shelter', 'Shelter', Icons.night_shelter_outlined),
    IconEntry('groups3', 'Groups', Icons.groups_3_outlined),
    IconEntry('escalator_warning', 'Kids', Icons.escalator_warning_outlined),
    IconEntry('pregnant', 'Parenting', Icons.pregnant_woman_outlined),
    IconEntry('person_add', 'Add Person', Icons.person_add_alt_1_outlined),
    IconEntry('manage_people', 'Manage', Icons.manage_accounts_outlined),
    IconEntry('military', 'Service', Icons.military_tech_outlined),
    IconEntry('psychology_p', 'Therapy', Icons.psychology_outlined),
    IconEntry('support_p', 'Support', Icons.support_agent_outlined),
    IconEntry('healing', 'Healing', Icons.healing_outlined),
    IconEntry('compassion', 'Compassion', Icons.favorite_border),
    IconEntry('adoption', 'Pets', Icons.pets_outlined),
    IconEntry('running_p', 'Active', Icons.directions_run_outlined),
    IconEntry('spa_p', 'Relax', Icons.self_improvement_outlined),
    IconEntry('person_outline', 'Profile', Icons.person_outline_outlined),
    IconEntry('supervisor_p', 'Mentor', Icons.supervisor_account_outlined),
    IconEntry('emoji_family', 'Family', Icons.family_restroom_outlined),
    IconEntry('reduce_capacity', 'Solo', Icons.reduce_capacity_outlined),
    IconEntry('how_to_reg', 'Register', Icons.how_to_reg_outlined),
  ]),
  IconCategory('Tech & Productivity', [
    IconEntry('computer', 'Computer', Icons.computer_outlined),
    IconEntry('mobile', 'Mobile', Icons.smartphone_outlined),
    IconEntry('coding', 'Coding', Icons.code_outlined),
    IconEntry('alarm', 'Alarm', Icons.alarm_outlined),
    IconEntry('timer', 'Timer', Icons.timer_outlined),
    IconEntry('focus', 'Focus', Icons.center_focus_strong_outlined),
    IconEntry('energy', 'Energy', Icons.bolt_outlined),
    IconEntry('cloud', 'Cloud', Icons.cloud_outlined),
    IconEntry('wifi', 'Connected', Icons.wifi_outlined),
    IconEntry('security', 'Security', Icons.security_outlined),
    IconEntry('settings', 'Settings', Icons.settings_outlined),
    IconEntry('notifications', 'Notify', Icons.notifications_outlined),
    IconEntry('av_timer', 'Countdown', Icons.av_timer_outlined),
    IconEntry('calendar', 'Calendar', Icons.calendar_month_outlined),
    IconEntry('snooze', 'Snooze', Icons.snooze_outlined),
    IconEntry('watch_later', 'Later', Icons.watch_later_outlined),
    IconEntry('hourglass', 'Hourglass', Icons.hourglass_empty_outlined),
    IconEntry('more_time', 'More Time', Icons.more_time_outlined),
    IconEntry('monitor', 'Monitor', Icons.monitor_outlined),
    IconEntry('router', 'Router', Icons.router_outlined),
    IconEntry('storage', 'Storage', Icons.storage_outlined),
    IconEntry('backup', 'Backup', Icons.backup_outlined),
    IconEntry('sync', 'Sync', Icons.sync_outlined),
    IconEntry('download', 'Download', Icons.download_outlined),
    IconEntry('upload', 'Upload', Icons.upload_outlined),
    IconEntry('terminal', 'Terminal', Icons.terminal_outlined),
    IconEntry('developer', 'Dev Mode', Icons.developer_mode_outlined),
    IconEntry('laptop', 'Laptop', Icons.laptop_outlined),
    IconEntry('tablet', 'Tablet', Icons.tablet_outlined),
    IconEntry('watch', 'Watch', Icons.watch_outlined),
    IconEntry('keyboard', 'Keyboard', Icons.keyboard_outlined),
    IconEntry('mouse', 'Mouse', Icons.mouse_outlined),
    IconEntry('headset', 'Headset', Icons.headset_outlined),
    IconEntry('printer_tech', 'Printer', Icons.local_printshop_outlined),
    IconEntry('scanner', 'Scanner', Icons.scanner_outlined),
    IconEntry('camera', 'Camera', Icons.camera_alt_outlined),
    IconEntry('usb', 'USB', Icons.usb_outlined),
    IconEntry('bluetooth', 'Bluetooth', Icons.bluetooth_outlined),
    IconEntry('nfc', 'NFC', Icons.nfc_outlined),
    IconEntry('vpn_key', 'Password', Icons.vpn_key_outlined),
    IconEntry('lock_tech', 'Lock', Icons.lock_outlined),
    IconEntry('bug_tech', 'Debug', Icons.bug_report_outlined),
    IconEntry('api', 'API', Icons.api_outlined),
    IconEntry('webhook', 'Webhook', Icons.webhook_outlined),
    IconEntry('dns', 'DNS', Icons.dns_outlined),
    IconEntry('cloud_upload', 'Deploy', Icons.cloud_upload_outlined),
    IconEntry('integration', 'Integrate', Icons.integration_instructions_outlined),
    IconEntry('data_object', 'Data', Icons.data_object_outlined),
    IconEntry('memory_tech', 'RAM', Icons.memory_outlined),
    IconEntry('battery', 'Battery', Icons.battery_full_outlined),
  ]),
  IconCategory('Transport & Commute', [
    IconEntry('train', 'Train', Icons.train_outlined),
    IconEntry('subway', 'Subway', Icons.directions_subway_outlined),
    IconEntry('bus', 'Bus', Icons.directions_bus_outlined),
    IconEntry('tram', 'Tram', Icons.tram_outlined),
    IconEntry('taxi', 'Taxi', Icons.local_taxi_outlined),
    IconEntry('motorcycle', 'Motorbike', Icons.motorcycle_outlined),
    IconEntry('electric_bike', 'E-Bike', Icons.electric_bike_outlined),
    IconEntry('electric_scooter', 'Scooter', Icons.electric_scooter_outlined),
    IconEntry('ev_station', 'EV Charge', Icons.ev_station_outlined),
    IconEntry('gas_station', 'Fuel', Icons.local_gas_station_outlined),
    IconEntry('parking', 'Parking', Icons.local_parking_outlined),
    IconEntry('traffic', 'Traffic', Icons.traffic_outlined),
    IconEntry('navigation_c', 'Navigate', Icons.navigation_outlined),
    IconEntry('alt_route', 'Route', Icons.alt_route_outlined),
    IconEntry('hail', 'Hail / Ride', Icons.hail_outlined),
    IconEntry('airport_shuttle', 'Shuttle', Icons.airport_shuttle_outlined),
    IconEntry('directions', 'Directions', Icons.directions_outlined),
    IconEntry('commute', 'Commute', Icons.commute_outlined),
    IconEntry('roundabout', 'Roundabout', Icons.roundabout_right_outlined),
    IconEntry('merge', 'Merge', Icons.merge_outlined),
    IconEntry('fork_right', 'Fork', Icons.fork_right_outlined),
    IconEntry('u_turn', 'U-Turn', Icons.u_turn_right_outlined),
    IconEntry('trip_origin', 'Origin', Icons.trip_origin_outlined),
    IconEntry('fleet', 'Fleet', Icons.directions_car_outlined),
    IconEntry('minivan', 'Van', Icons.airport_shuttle_outlined),
    IconEntry('boat', 'Boat', Icons.directions_boat_outlined),
    IconEntry('bike_share', 'Bike Share', Icons.pedal_bike_outlined),
    IconEntry('wrong_location', 'Detour', Icons.wrong_location_outlined),
    IconEntry('transfer', 'Transfer', Icons.transfer_within_a_station_outlined),
    IconEntry('departure', 'Depart', Icons.flight_takeoff_outlined),
    IconEntry('arrival', 'Arrive', Icons.flight_land_outlined),
    IconEntry('distance', 'Distance', Icons.social_distance_outlined),
    IconEntry('time_to_leave', 'Leave', Icons.time_to_leave_outlined),
    IconEntry('location_city', 'City', Icons.location_city_outlined),
    IconEntry('moving_truck', 'Moving', Icons.local_shipping_outlined),
  ]),
  IconCategory('Animals & Nature', [
    IconEntry('pets', 'Pets', Icons.pets_outlined),
    IconEntry('cruelty_free', 'Vegan', Icons.cruelty_free_outlined),
    IconEntry('bug', 'Bug', Icons.bug_report_outlined),
    IconEntry('pest_control', 'Pest', Icons.pest_control_outlined),
    IconEntry('park_nature', 'Park', Icons.park_outlined),
    IconEntry('emoji_nature', 'Nature', Icons.emoji_nature_outlined),
    IconEntry('energy_leaf', 'Green', Icons.energy_savings_leaf_outlined),
    IconEntry('recycling', 'Recycle', Icons.recycling_outlined),
    IconEntry('compost', 'Compost', Icons.compost_outlined),
    IconEntry('air', 'Air', Icons.air_outlined),
    IconEntry('solar', 'Solar', Icons.solar_power_outlined),
    IconEntry('wind', 'Wind', Icons.wind_power_outlined),
    IconEntry('grain', 'Grain', Icons.grain_outlined),
    IconEntry('flood', 'Flood', Icons.flood_outlined),
    IconEntry('landslide', 'Earth', Icons.landslide_outlined),
    IconEntry('thunderstorm_n', 'Storm', Icons.thunderstorm_outlined),
    IconEntry('ac_nature', 'Snow', Icons.ac_unit_outlined),
    IconEntry('forest_n', 'Forest', Icons.forest_outlined),
    IconEntry('grass_n', 'Grass', Icons.grass_outlined),
    IconEntry('terrain_n', 'Mountain', Icons.terrain_outlined),
    IconEntry('agriculture_n', 'Farm', Icons.agriculture_outlined),
    IconEntry('tsunami_n', 'Wave', Icons.tsunami_outlined),
    IconEntry('local_florist_n', 'Flower', Icons.local_florist_outlined),
    IconEntry('leaf_eco', 'Eco', Icons.eco_outlined),
    IconEntry('nature_n', 'Leaf', Icons.nature_outlined),
    IconEntry('water_nature', 'Water', Icons.water_outlined),
    IconEntry('wb_cloudy', 'Cloudy', Icons.wb_cloudy_outlined),
    IconEntry('rainbow_n', 'Rainbow', Icons.filter_drama_outlined),
    IconEntry('sunny_n', 'Sunny', Icons.wb_sunny_outlined),
    IconEntry('nights_stay_n', 'Night', Icons.nights_stay_outlined),
    IconEntry('spa_nature', 'Bloom', Icons.spa_outlined),
    IconEntry('yard_n', 'Yard', Icons.yard_outlined),
    IconEntry('heat', 'Heatwave', Icons.thermostat_outlined),
    IconEntry('foggy', 'Foggy', Icons.foggy),
    IconEntry('device_thermostat', 'Temperature', Icons.device_thermostat_outlined),
    IconEntry('water_damage', 'Damp', Icons.water_damage_outlined),
    IconEntry('dark_mode_n', 'Dark Sky', Icons.dark_mode_outlined),
    IconEntry('light_mode_n', 'Clear', Icons.light_mode_outlined),
    IconEntry('partly_cloudy', 'Partly Cloudy', Icons.wb_cloudy_outlined),
    IconEntry('backpack', 'Outdoors', Icons.backpack_outlined),
  ]),
  IconCategory('Communication', [
    IconEntry('message', 'Message', Icons.message_outlined),
    IconEntry('email', 'Email', Icons.email_outlined),
    IconEntry('chat_comm', 'Chat', Icons.chat_outlined),
    IconEntry('forum_comm', 'Forum', Icons.forum_outlined),
    IconEntry('sms', 'SMS', Icons.sms_outlined),
    IconEntry('call', 'Call', Icons.call_outlined),
    IconEntry('video_call', 'Video Call', Icons.video_call_outlined),
    IconEntry('inbox', 'Inbox', Icons.inbox_outlined),
    IconEntry('mark_read', 'Read', Icons.mark_chat_read_outlined),
    IconEntry('rss', 'Blog', Icons.rss_feed_outlined),
    IconEntry('send', 'Send', Icons.send_outlined),
    IconEntry('reply', 'Reply', Icons.reply_outlined),
    IconEntry('forward', 'Forward', Icons.forward_to_inbox_outlined),
    IconEntry('comment', 'Comment', Icons.comment_outlined),
    IconEntry('rate_review', 'Review', Icons.rate_review_outlined),
    IconEntry('contact_mail', 'Contact', Icons.contact_mail_outlined),
    IconEntry('contact_phone', 'Phone', Icons.contact_phone_outlined),
    IconEntry('campaign_c', 'Broadcast', Icons.campaign_outlined),
    IconEntry('announcement_c', 'News', Icons.announcement_outlined),
    IconEntry('notifications_c', 'Alert', Icons.notifications_active_outlined),
    IconEntry('speaker_notes', 'Notes', Icons.speaker_notes_outlined),
    IconEntry('feedback_c', 'Feedback', Icons.feedback_outlined),
    IconEntry('question_answer', 'Q&A', Icons.question_answer_outlined),
    IconEntry('support', 'Support', Icons.support_agent_outlined),
    IconEntry('hearing', 'Listen', Icons.hearing_outlined),
    IconEntry('record_comm', 'Record', Icons.mic_outlined),
    IconEntry('interpreter_c', 'Interpret', Icons.interpreter_mode_outlined),
    IconEntry('language_c', 'Language', Icons.language_outlined),
    IconEntry('share_c', 'Share', Icons.share_outlined),
    IconEntry('wifi_calling', 'Online', Icons.wifi_calling_outlined),
    IconEntry('live_help', 'Help', Icons.live_help_outlined),
    IconEntry('mark_unread', 'Unread', Icons.mark_chat_unread_outlined),
    IconEntry('quick_reply', 'Quick', Icons.quickreply_outlined),
    IconEntry('textsms', 'Text', Icons.textsms_outlined),
    IconEntry('voicemail', 'Voicemail', Icons.voicemail_outlined),
    IconEntry('call_missed', 'Missed', Icons.call_missed_outlined),
    IconEntry('phone_callback', 'Callback', Icons.phone_callback_outlined),
    IconEntry('perm_phone', 'Phone Book', Icons.perm_phone_msg_outlined),
    IconEntry('contact_emergency', 'Emergency', Icons.contact_emergency_outlined),
    IconEntry('social_distance', 'Distance', Icons.social_distance_outlined),
  ]),
  IconCategory('Events & Occasions', [
    IconEntry('party', 'Party', Icons.celebration_outlined),
    IconEntry('birthday', 'Birthday', Icons.cake_outlined),
    IconEntry('gift', 'Gift', Icons.card_giftcard_outlined),
    IconEntry('nightlife', 'Nightlife', Icons.nightlife_outlined),
    IconEntry('confirmation_num', 'Ticket', Icons.confirmation_number_outlined),
    IconEntry('museum_e', 'Museum', Icons.museum_outlined),
    IconEntry('church_e', 'Church', Icons.church_outlined),
    IconEntry('mosque_e', 'Mosque', Icons.mosque_outlined),
    IconEntry('synagogue_e', 'Synagogue', Icons.synagogue_outlined),
    IconEntry('temple_buddhist_e', 'Temple', Icons.temple_buddhist_outlined),
    IconEntry('temple_hindu_e', 'Hindu Temple', Icons.temple_hindu_outlined),
    IconEntry('stadium', 'Stadium', Icons.stadium_outlined),
    IconEntry('sports_score', 'Game Day', Icons.sports_score_outlined),
    IconEntry('local_activity', 'Activity', Icons.local_activity_outlined),
    IconEntry('theater_e', 'Theater', Icons.theaters_outlined),
    IconEntry('casino', 'Casino', Icons.casino_outlined),
    IconEntry('local_play', 'Show', Icons.local_play_outlined),
    IconEntry('wine_bar_e', 'Wine Night', Icons.wine_bar_outlined),
    IconEntry('outdoor_bbq', 'BBQ', Icons.outdoor_grill_outlined),
    IconEntry('firepit', 'Bonfire', Icons.fireplace_outlined),
    IconEntry('festival', 'Festival', Icons.festival_outlined),
    IconEntry('parade', 'Parade', Icons.emoji_people_outlined),
    IconEntry('wedding', 'Wedding', Icons.favorite_border),
    IconEntry('anniversary', 'Anniversary', Icons.favorite_border),
    IconEntry('graduation', 'Graduation', Icons.school_outlined),
    IconEntry('new_year', 'New Year', Icons.rocket_launch_outlined),
    IconEntry('holiday', 'Holiday', Icons.beach_access_outlined),
    IconEntry('movie_night', 'Movie Night', Icons.local_movies_outlined),
    IconEntry('game_night', 'Game Night', Icons.games_outlined),
    IconEntry('concert', 'Concert', Icons.music_note_outlined),
  ]),
  IconCategory('Mindfulness & Mental Health', [
    IconEntry('mindful', 'Mindfulness', Icons.self_improvement_outlined),
    IconEntry('breathe', 'Breathe', Icons.air_outlined),
    IconEntry('journal', 'Journal', Icons.book_outlined),
    IconEntry('gratitude', 'Gratitude', Icons.favorite_border),
    IconEntry('reflect', 'Reflect', Icons.psychology_outlined),
    IconEntry('calm', 'Calm', Icons.spa_outlined),
    IconEntry('therapy_m', 'Therapy', Icons.psychology_alt_outlined),
    IconEntry('mood_track', 'Mood Track', Icons.mood_outlined),
    IconEntry('positive', 'Positive', Icons.sentiment_very_satisfied_outlined),
    IconEntry('affirmation', 'Affirmations', Icons.format_quote_outlined),
    IconEntry('bedtime_m', 'Sleep', Icons.bedtime_outlined),
    IconEntry('morning', 'Morning', Icons.wb_sunny_outlined),
    IconEntry('sunset', 'Evening', Icons.nights_stay_outlined),
    IconEntry('no_phone', 'Detox', Icons.smartphone_outlined),
    IconEntry('nature_m', 'Nature Walk', Icons.nature_people_outlined),
    IconEntry('music_m', 'Music', Icons.headphones_outlined),
    IconEntry('reading_m', 'Reading', Icons.auto_stories_outlined),
    IconEntry('creativity', 'Creative', Icons.palette_outlined),
    IconEntry('hydration', 'Hydrate', Icons.local_drink_outlined),
    IconEntry('movement', 'Movement', Icons.directions_run_outlined),
    IconEntry('stretching', 'Stretch', Icons.sports_gymnastics),
    IconEntry('sun_salutation', 'Yoga', Icons.self_improvement_outlined),
    IconEntry('community_m', 'Community', Icons.groups_outlined),
    IconEntry('volunteer_m', 'Give Back', Icons.volunteer_activism_outlined),
    IconEntry('simplify', 'Simplify', Icons.minimize_outlined),
    IconEntry('digital_wellbeing', 'Screen Time', Icons.monitor_heart_outlined),
    IconEntry('offline', 'Offline', Icons.wifi_off_outlined),
    IconEntry('do_not_disturb', 'Focus', Icons.do_not_disturb_outlined),
    IconEntry('notifications_off', 'Quiet', Icons.notifications_off_outlined),
    IconEntry('healing_m', 'Healing', Icons.healing_outlined),
  ]),
];

/// Flat lookup map: name → IconEntry. Built once at startup.
final Map<String, IconEntry> iconByName = {
  for (final cat in iconCatalog)
    for (final entry in cat.entries) entry.name: entry,
};

/// Returns the IconData for a stored goal icon name, or null if not found.
/// Null means the stored value is a legacy Unicode emoji string.
IconData? iconDataForName(String name) => iconByName[name]?.icon;
