import 'package:collection/collection.dart';
import '../models/enums.dart';
import '../models/sub_task.dart';

class Goal {
  final String goalId;
  String title;
  String notes;
  GoalStatus status;
  GoalDifficulty difficulty;
  DateTime? dueDate;
  // Single emoji generated by the LLM to visually represent this goal.
  // Null when generation is disabled or the goal was created before the feature.
  String? emoji;
  final List<SubTask> subtasks;

  Goal({
    required this.goalId,
    required this.title,
    this.notes = '',
    this.status = GoalStatus.active,
    this.difficulty = GoalDifficulty.easy,
    this.dueDate,
    this.emoji,
    List<SubTask>? subtasks,
  }) : subtasks = subtasks ?? [];

  // --- Computed properties ---

  bool get isCompleted => status == GoalStatus.completed;

  bool get isDailyAssignable =>
      status != GoalStatus.completed && status != GoalStatus.inbox;

  // The subtask the user should work on right now
  // Always the first non-completed subtask — inProgress is implicit
  SubTask? get currentSubTask =>
      subtasks.firstWhereOrNull((t) => t.state == SubTaskState.pending);

  // The next subtask after the current one — for the "peek" in Focus screen
  SubTask? get nextSubTask {
    final current = currentSubTask;
    if (current == null) return null;

    final currentIndex = subtasks.indexOf(current);
    final remaining = subtasks.skip(currentIndex + 1);
    return remaining.firstWhereOrNull((t) => t.state == SubTaskState.pending);
  }

  // Used by the UI to decide how to render each subtask tile
  bool isCurrentSubTask(SubTask subtask) => subtask == currentSubTask;

  int get completedSubtaskCount =>
      subtasks.where((t) => t.state == SubTaskState.completed).length;

  double get progressPercent =>
      subtasks.isEmpty ? 0 : completedSubtaskCount / subtasks.length;

  // --- Mutations ---

  void addSubTask(SubTask task) {
    subtasks.add(task);
    _recalculateStatus();
  }

  // Discards all existing subtasks and replaces them with a fresh list.
  // Completion state is reset; goal status is recalculated afterward.
  void replaceAllSubTasks(List<SubTask> newSubtasks) {
    subtasks
      ..clear()
      ..addAll(newSubtasks);
    _recalculateStatus();
  }

  // Removes all pending subtasks and appends newSubtasks after any completed
  // ones, preserving the completed steps in place.
  void replacePendingSubTasks(List<SubTask> newSubtasks) {
    subtasks.removeWhere((t) => t.state == SubTaskState.pending);
    subtasks.addAll(newSubtasks);
    _recalculateStatus();
  }

  // Replaces a single subtask in-place with one or more replacements,
  // preserving list order. Used for splitting a subtask into smaller steps.
  void replaceSubTask(String subtaskId, List<SubTask> replacements) {
    final index = subtasks.indexWhere((t) => t.subtaskId == subtaskId);
    if (index == -1) return;
    subtasks.removeAt(index);
    subtasks.insertAll(index, replacements);
  }

  void removeSubTask(String subtaskId) {
    subtasks.removeWhere((t) => t.subtaskId == subtaskId);
    _recalculateStatus();
  }

  // Complete the current subtask — next pending one becomes current implicitly
  void completeCurrentSubTask() {
    final current = currentSubTask;
    if (current == null) return;

    current.markComplete();
    _recalculateStatus();
  }

  /// Completes a specific subtask by ID. Throws [StateError] if [subtaskId] is
  /// not the first-pending subtask — completion is strictly sequential.
  ///
  /// Use [completeCurrentSubTask] when you always want to advance the sequence
  /// without specifying an ID. Use this method when the caller needs to assert
  /// it is targeting the right step (e.g. the Focus screen's completion button).
  void completeSubTask(String subtaskId) {
    final current = currentSubTask;
    if (current == null || current.subtaskId != subtaskId) {
      throw StateError(
        'Cannot complete subtask "$subtaskId" out of order; '
        'first pending subtask is "${current?.subtaskId ?? "none"}".',
      );
    }
    current.markComplete();
    _recalculateStatus();
  }

  // Undo a completed subtask — reinserts just before the current subtask
  // so it becomes the new current
  void uncompleteSubTask(String subtaskId) {
    final subtask = subtasks.firstWhereOrNull((t) => t.subtaskId == subtaskId);
    if (subtask == null || subtask.state != SubTaskState.completed) return;

    subtask.markIncomplete();
    subtasks.remove(subtask);

    // Find the current subtask after removal — nullable, handled explicitly
    final current = currentSubTask;
    final insertAt = current == null
        ? subtasks
              .length // no pending subtasks — append to end
        : subtasks.indexOf(current); // insert just before current

    subtasks.insert(insertAt, subtask);
    _recalculateStatus();
  }

  void reorderSubTask(int oldIndex, int newIndex) {
    if (newIndex > oldIndex) newIndex -= 1;
    final movingTask = subtasks[oldIndex];
    if (movingTask.state == SubTaskState.completed) return;

    final firstPendingIndex = subtasks.indexWhere(
      (t) => t.state == SubTaskState.pending,
    );
    if (newIndex < firstPendingIndex) {
      newIndex = firstPendingIndex;
    }

    subtasks.removeAt(oldIndex);
    subtasks.insert(newIndex, movingTask);
  }

  void _recalculateStatus() {
    // Inbox goals stay in the planning stage until the user explicitly
    // queues them via GoalService.queueGoal(). Archived goals are frozen.
    if (status == GoalStatus.archived || status == GoalStatus.inbox) return;
    final allDone =
        subtasks.isNotEmpty &&
        subtasks.every((t) => t.state == SubTaskState.completed);
    status = allDone ? GoalStatus.completed : GoalStatus.active;
  }

  // --- Serialisation ---

  Map<String, dynamic> toJson() => {
    'goalId': goalId,
    'title': title,
    'notes': notes,
    'status': status.name,
    'difficulty': difficulty.name,
    'dueDate': dueDate?.toIso8601String(),
    'emoji': emoji,
    'subtasks': subtasks.map((t) => t.toJson()).toList(),
  };

  factory Goal.fromJson(Map<String, dynamic> json) {
    return Goal(
      goalId: json['goalId'] as String,
      title: json['title'] as String,
      notes: json['notes'] as String? ?? '',
      status: GoalStatus.values.byName(json['status'] as String),
      difficulty: GoalDifficulty.values.asNameMap()[json['difficulty'] as String? ?? ''] ??
          GoalDifficulty.easy,
      dueDate: json['dueDate'] != null
          ? DateTime.parse(json['dueDate'] as String)
          : null,
      emoji: json['emoji'] as String?,
      subtasks:
          (json['subtasks'] as List<dynamic>?)
              ?.map((t) => SubTask.fromJson(t as Map<String, dynamic>))
              .toList() ??
          [],
    );
  }
}
