import 'package:collection/collection.dart';
import '../models/enums.dart';
import '../models/recurrence.dart';
import '../models/sub_task.dart';

class Goal {
  final String goalId;
  String title;
  String notes;
  GoalStatus status;
  GoalDifficulty difficulty;
  DateTime? dueDate;
  // Single emoji generated by the LLM to visually represent this goal.
  // Null when generation is disabled or the goal was created before the feature.
  String? emoji;
  final List<SubTask> subtasks;

  // ── Recurrence ──────────────────────────────────────────────────────────
  //
  // A goal can repeat on a schedule. When set, the [SchedulingService]
  // monitors [nextOccurrenceAt] and resets all subtasks to pending when the
  // next occurrence arrives. The previous cycle's progress is captured in
  // [lastIterationSummary] so a (future) LLM "re-plan" flow can use it as
  // context when generating fresh steps for the new cycle.
  //
  // Null = one-shot goal (today's behaviour, no change).

  /// The recurrence pattern, or null for a one-shot goal.
  Recurrence? recurrence;

  /// Pre-computed time at which the next reset is due. Set whenever the
  /// recurrence pattern changes or a cycle resets. Null when [recurrence]
  /// is null.
  DateTime? nextOccurrenceAt;

  /// Free-text summary of what the user completed in the previous cycle.
  /// Stays small (a couple hundred chars) so it can be passed straight to
  /// an LLM as part of a prompt without context-window concerns.
  /// Empty before the first reset.
  String lastIterationSummary;

  /// When the previous cycle ended (recurrence reset). Used by the sort
  /// to mark goals that have a freshly-revived current step as "Resumed".
  DateTime? lastResumedAt;

  /// When the goal was first captured. Set by the creation paths in
  /// [GoalDecompositionService]. Null for goals created before this field
  /// existed — the UI simply omits the "Created" metadata in that case.
  final DateTime? createdAt;

  Goal({
    required this.goalId,
    required this.title,
    this.notes = '',
    this.status = GoalStatus.active,
    this.difficulty = GoalDifficulty.easy,
    this.dueDate,
    this.emoji,
    List<SubTask>? subtasks,
    this.recurrence,
    this.nextOccurrenceAt,
    this.lastIterationSummary = '',
    this.lastResumedAt,
    this.createdAt,
  }) : subtasks = subtasks ?? [];

  // --- Computed properties ---

  bool get isCompleted => status == GoalStatus.completed;

  bool get isDailyAssignable =>
      status != GoalStatus.completed && status != GoalStatus.inbox;

  /// True when the recurrence pattern is set (recurring goal).
  bool get isRecurring => recurrence != null;

  /// True when the first non-completed subtask is snoozed. The goal is
  /// effectively "on hold" — [currentSubTask] returns null and the sort
  /// pushes it to the bottom.
  bool get isOnHold {
    final firstActive =
        subtasks.firstWhereOrNull((t) => t.state != SubTaskState.completed);
    return firstActive?.state == SubTaskState.snoozed;
  }

  /// The subtask the user should work on right now.
  ///
  /// Returns the first pending subtask in order. **Returns null when the
  /// first non-completed subtask is snoozed** — that means the goal is on
  /// hold and the user shouldn't be skipped ahead to a later step.
  SubTask? get currentSubTask {
    final firstActive =
        subtasks.firstWhereOrNull((t) => t.state != SubTaskState.completed);
    if (firstActive == null) return null; // every subtask is completed
    if (firstActive.state == SubTaskState.snoozed) return null; // on hold
    return firstActive;
  }

  // The next subtask after the current one — for the "peek" in Focus screen
  SubTask? get nextSubTask {
    final current = currentSubTask;
    if (current == null) return null;

    final currentIndex = subtasks.indexOf(current);
    final remaining = subtasks.skip(currentIndex + 1);
    return remaining.firstWhereOrNull((t) => t.state == SubTaskState.pending);
  }

  // Used by the UI to decide how to render each subtask tile
  bool isCurrentSubTask(SubTask subtask) => subtask == currentSubTask;

  int get completedSubtaskCount =>
      subtasks.where((t) => t.state == SubTaskState.completed).length;

  double get progressPercent =>
      subtasks.isEmpty ? 0 : completedSubtaskCount / subtasks.length;

  /// When the goal was finished — the latest completion date among its
  /// subtasks. Null unless the goal is currently [GoalStatus.completed].
  DateTime? get completedAt {
    if (status != GoalStatus.completed) return null;
    DateTime? latest;
    for (final st in subtasks) {
      final c = st.completionDate;
      if (c != null && (latest == null || c.isAfter(latest))) latest = c;
    }
    return latest;
  }

  // --- Mutations ---

  void addSubTask(SubTask task) {
    subtasks.add(task);
    _recalculateStatus();
  }

  // Discards all existing subtasks and replaces them with a fresh list.
  // Completion state is reset; goal status is recalculated afterward.
  void replaceAllSubTasks(List<SubTask> newSubtasks) {
    subtasks
      ..clear()
      ..addAll(newSubtasks);
    _recalculateStatus();
  }

  // Removes all pending subtasks and appends newSubtasks after any completed
  // ones, preserving the completed steps in place.
  void replacePendingSubTasks(List<SubTask> newSubtasks) {
    subtasks.removeWhere((t) => t.state == SubTaskState.pending);
    subtasks.addAll(newSubtasks);
    _recalculateStatus();
  }

  // Replaces a single subtask in-place with one or more replacements,
  // preserving list order. Used for splitting a subtask into smaller steps.
  void replaceSubTask(String subtaskId, List<SubTask> replacements) {
    final index = subtasks.indexWhere((t) => t.subtaskId == subtaskId);
    if (index == -1) return;
    subtasks.removeAt(index);
    subtasks.insertAll(index, replacements);
  }

  void removeSubTask(String subtaskId) {
    subtasks.removeWhere((t) => t.subtaskId == subtaskId);
    _recalculateStatus();
  }

  void clearSubtasks() {
    subtasks.clear();
    _recalculateStatus();
  }

  // Complete the current subtask — next pending one becomes current implicitly
  void completeCurrentSubTask() {
    final current = currentSubTask;
    if (current == null) return;

    current.markComplete();
    _recalculateStatus();
    _applyAutoSleepToNewCurrent();
  }

  /// Completes a specific subtask by ID. Throws [StateError] if [subtaskId] is
  /// not the first-pending subtask — completion is strictly sequential.
  ///
  /// Use [completeCurrentSubTask] when you always want to advance the sequence
  /// without specifying an ID. Use this method when the caller needs to assert
  /// it is targeting the right step (e.g. the Focus screen's completion button).
  void completeSubTask(String subtaskId) {
    final current = currentSubTask;
    if (current == null || current.subtaskId != subtaskId) {
      throw StateError(
        'Cannot complete subtask "$subtaskId" out of order; '
        'first pending subtask is "${current?.subtaskId ?? "none"}".',
      );
    }
    current.markComplete();
    _recalculateStatus();
    _applyAutoSleepToNewCurrent();
  }

  /// If the (newly promoted) current subtask carries an
  /// [SubTask.autoSleepDuration], snooze it for that duration and clear
  /// the field so the trigger is one-shot. Called from any code path that
  /// advances the queue.
  void _applyAutoSleepToNewCurrent() {
    final next = currentSubTask;
    if (next == null) return;
    final delay = next.autoSleepDuration;
    if (delay == null) return;
    // Only snooze if the delay is positive — defensive against bad inputs.
    if (delay.inSeconds <= 0) {
      next.autoSleepDuration = null;
      return;
    }
    next.snooze(DateTime.now().add(delay));
    // One-shot: clear the configured duration so a future
    // un-complete / re-complete cycle doesn't re-snooze the same step.
    next.autoSleepDuration = null;
  }

  /// Snoozes the current subtask until [until]. Throws [StateError] when
  /// there is no current subtask (goal already on hold or completed). This
  /// is the only entry point — snoozing a non-current pending subtask is
  /// disallowed since the sequential ordering would still block it.
  void snoozeCurrentSubTask(DateTime until, {bool notify = false}) {
    final current = currentSubTask;
    if (current == null) {
      throw StateError(
        'Cannot snooze: goal has no current subtask '
        '(already on hold or completed).',
      );
    }
    current.snooze(until, notify: notify);
  }

  /// Wakes a snoozed subtask immediately by ID. No-op if the subtask isn't
  /// snoozed. Used by manual "wake now" actions and by the
  /// [SchedulingService] when [SubTask.snoozedUntil] passes.
  void wakeSubTask(String subtaskId) {
    final subtask =
        subtasks.firstWhereOrNull((t) => t.subtaskId == subtaskId);
    if (subtask == null) return;
    subtask.wakeUp();
  }

  // Undo a completed subtask — reinserts just before the current subtask
  // so it becomes the new current
  void uncompleteSubTask(String subtaskId) {
    final subtask = subtasks.firstWhereOrNull((t) => t.subtaskId == subtaskId);
    if (subtask == null || subtask.state != SubTaskState.completed) return;

    subtask.markIncomplete();
    subtasks.remove(subtask);

    // Find the current subtask after removal — nullable, handled explicitly
    final current = currentSubTask;
    final insertAt = current == null
        ? subtasks
              .length // no pending subtasks — append to end
        : subtasks.indexOf(current); // insert just before current

    subtasks.insert(insertAt, subtask);
    _recalculateStatus();
  }

  void reorderSubTask(int oldIndex, int newIndex) {
    if (newIndex > oldIndex) newIndex -= 1;
    final movingTask = subtasks[oldIndex];
    if (movingTask.state == SubTaskState.completed) return;

    final firstPendingIndex = subtasks.indexWhere(
      (t) => t.state == SubTaskState.pending,
    );
    if (newIndex < firstPendingIndex) {
      newIndex = firstPendingIndex;
    }

    subtasks.removeAt(oldIndex);
    subtasks.insert(newIndex, movingTask);
  }

  // ── Recurrence operations ────────────────────────────────────────────────

  /// Resets every subtask back to [SubTaskState.pending] and records a
  /// brief summary of what was just completed in [lastIterationSummary] so
  /// the next iteration can reference it (e.g. for LLM-driven re-planning).
  ///
  /// This is the single domain-level entry point for cycling a recurring
  /// goal. [SchedulingService] calls it at the configured occurrence time;
  /// the UI can also expose a manual "Start a new cycle" button.
  void resetRecurrenceCycle({DateTime? now}) {
    final stamp = now ?? DateTime.now();
    // Capture completed-step descriptions before we reset them.
    final completedDescs = subtasks
        .where((t) => t.state == SubTaskState.completed)
        .map((t) => t.description)
        .toList();
    lastIterationSummary = _buildIterationSummary(completedDescs);

    // Flip all subtasks back to pending (and clear any snooze state).
    for (final st in subtasks) {
      st.state = SubTaskState.pending;
      st.completionDate = null;
      st.snoozedUntil = null;
      st.notifyOnWake = false;
      st.lastSeenDate = stamp;
    }

    lastResumedAt = stamp;
    if (recurrence != null) {
      nextOccurrenceAt = recurrence!.nextOccurrenceAfter(stamp);
    }
    _recalculateStatus();
  }

  /// Builds a compact iteration summary string from completed step
  /// descriptions. Capped to ~280 chars so it stays cheap to embed in
  /// future LLM prompts.
  String _buildIterationSummary(List<String> completedDescs) {
    if (completedDescs.isEmpty) {
      return 'No steps completed last cycle.';
    }
    final joined = completedDescs.map((d) => '• $d').join('\n');
    if (joined.length <= 280) return joined;
    return '${joined.substring(0, 277)}…';
  }

  void _recalculateStatus() {
    // Inbox goals stay in the planning stage until the user explicitly
    // queues them via GoalService.queueGoal(). Archived goals are frozen.
    if (status == GoalStatus.archived || status == GoalStatus.inbox) return;
    final allDone =
        subtasks.isNotEmpty &&
        subtasks.every((t) => t.state == SubTaskState.completed);
    status = allDone ? GoalStatus.completed : GoalStatus.active;
  }

  // --- Serialisation ---

  Map<String, dynamic> toJson() => {
        'goalId': goalId,
        'title': title,
        'notes': notes,
        'status': status.name,
        'difficulty': difficulty.name,
        'dueDate': dueDate?.toIso8601String(),
        'emoji': emoji,
        'subtasks': subtasks.map((t) => t.toJson()).toList(),
        if (recurrence != null) 'recurrence': recurrence!.toJson(),
        if (nextOccurrenceAt != null)
          'nextOccurrenceAt': nextOccurrenceAt!.toIso8601String(),
        if (lastIterationSummary.isNotEmpty)
          'lastIterationSummary': lastIterationSummary,
        if (lastResumedAt != null)
          'lastResumedAt': lastResumedAt!.toIso8601String(),
        if (createdAt != null) 'createdAt': createdAt!.toIso8601String(),
      };

  factory Goal.fromJson(Map<String, dynamic> json) {
    return Goal(
      goalId: json['goalId'] as String,
      title: json['title'] as String,
      notes: json['notes'] as String? ?? '',
      status: GoalStatus.values.byName(json['status'] as String),
      difficulty: GoalDifficulty.values.asNameMap()[json['difficulty'] as String? ?? ''] ??
          GoalDifficulty.easy,
      dueDate: json['dueDate'] != null
          ? DateTime.parse(json['dueDate'] as String)
          : null,
      emoji: json['emoji'] as String?,
      subtasks:
          (json['subtasks'] as List<dynamic>?)
              ?.map((t) => SubTask.fromJson(t as Map<String, dynamic>))
              .toList() ??
          [],
      recurrence: json['recurrence'] != null
          ? Recurrence.fromJson(
              (json['recurrence'] as Map).cast<String, dynamic>())
          : null,
      nextOccurrenceAt: json['nextOccurrenceAt'] != null
          ? DateTime.parse(json['nextOccurrenceAt'] as String)
          : null,
      lastIterationSummary: json['lastIterationSummary'] as String? ?? '',
      lastResumedAt: json['lastResumedAt'] != null
          ? DateTime.parse(json['lastResumedAt'] as String)
          : null,
      createdAt: json['createdAt'] != null
          ? DateTime.parse(json['createdAt'] as String)
          : null,
    );
  }
}
